### ISSUE TITLE
Dependency of a git project from other existing projects

### ISSUE THREAD

**Issue by huddletest** [irfanshamid/football-lineup-builder#3]
@irfanshamid 
how I can remove this dependency? I mean I am interested to only use a copy ?
`git checkout -b localbranch` without remove last change

**Comment by irfanshamid** [comment]
let check your git stage. add all your last change into stage before checkout to another branch ✌️

**Comment by huddletest** [comment]
> let check your git stage. add all your last change into stage before checkout to another branch ✌️

okeeyy thank you

**Comment by irfanshamid** [comment]
> > let check your git stage. add all your last change into stage before checkout to another branch ✌️
> 
> okeeyy thank you

make sure that you already fork my latest feature budd
